/* Script de inserción de datos de prueba Proyecto Zeus */

/* Tabla info_usuario */

DELETE FROM `info_usuario`;

INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('01','User 1','Usuario de prueba 1','User1@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('02','User 2','Usuario de prueba 2','User2@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('03','User 3','Usuario de prueba 3','User3@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('04','User 4','Usuario de prueba 4','User4@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('05','User 5','Usuario de prueba 5','User5@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('06','User 6','Usuario de prueba 6','User6@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('07','User 7','Usuario de prueba 7','User7@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('08','User 8','Usuario de prueba 8','User8@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('09','User 9','Usuario de prueba 9','User9@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('10','User 10','Usuario de prueba 10','User10@AGUW.cl',SYSDATE(),'2012/01/01');

INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('11','User 11','Usuario de prueba 11','User11@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('12','User 12','Usuario de prueba 12','User12@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('13','User 13','Usuario de prueba 13','User13@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('14','User 14','Usuario de prueba 14','User14@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('15','User 15','Usuario de prueba 15','User15@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('16','User 16','Usuario de prueba 16','User16@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('17','User 17','Usuario de prueba 17','User17@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('18','User 18','Usuario de prueba 18','User18@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('19','User 19','Usuario de prueba 19','User19@AGUW.cl',SYSDATE(),'2012/01/01');
INSERT INTO `info_usuario`(`ID_USUARIO`, `NOMBRE_USUARIO`, `DESCRIPCION_USUARIO`, `EMAIL`, `FECHA_REGISTRO`, `FECHA_NACIMIENTO`) VALUES ('20','User 20','Usuario de prueba 20','User20@AGUW.cl',SYSDATE(),'2012/01/01');


COMMIT;




